# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91fd52d0c07083e877d41d69857e2fb9cf7677ca587dc69806ce711c2a68ef4072e145d0bc00edc732c7b86fdc3c4fc9193339941de5e78ec19686e226311577

test:
  secret_key_base: 46ab876b68055937b2f10c75ac6953d73037ca79b25f9ac7f97f2519791393bd3a38f7f876e00a45ea12b9c38266f7e74c3a798532600d94768ebc707797f986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
